resource "sdwan_sse_zscaler_feature" "sse_zscaler_feature" {
  for_each = {
    for zscaler_item in flatten([
      for profile in try(local.feature_profiles.sse_profiles, []) :
      try(profile.zscaler, null) != null ? [{
        profile = profile
        zscaler = profile.zscaler
      }] : []
    ])
    : "${zscaler_item.profile.name}-zscaler" => zscaler_item
  }
  name                                   = each.value.zscaler.name
  description                            = try(each.value.zscaler.description, null)
  feature_profile_id                     = sdwan_sse_feature_profile.sse_feature_profile[each.value.profile.name].id
  aup_enabled                            = try(each.value.zscaler.aup_enabled, null)
  aup_enabled_variable                   = try("{{${each.value.zscaler.aup_enabled_variable}}}", null)
  aup_timeout                            = try(each.value.zscaler.aup_timeout, null)
  aup_timeout_variable                   = try("{{${each.value.zscaler.aup_timeout_variable}}}", null)
  auth_required                          = try(each.value.zscaler.auth_required, null)
  auth_required_variable                 = try("{{${each.value.zscaler.auth_required_variable}}}", null)
  block_internet_until_accepted          = try(each.value.zscaler.block_internet_until_accepted, null)
  block_internet_until_accepted_variable = try("{{${each.value.zscaler.block_internet_until_accepted_variable}}}", null)
  caution_enabled                        = try(each.value.zscaler.caution_enabled, null)
  caution_enabled_variable               = try("{{${each.value.zscaler.caution_enabled_variable}}}", null)
  country                                = try(each.value.zscaler.country, null)
  country_variable                       = try("{{${each.value.zscaler.country_variable}}}", null)
  display_time_unit                      = try(each.value.zscaler.display_time_unit, null)
  display_time_unit_variable             = try("{{${each.value.zscaler.display_time_unit_variable}}}", null)
  dn_bandwidth                           = try(each.value.zscaler.download_bandwidth, null)
  dn_bandwidth_variable                  = try("{{${each.value.zscaler.download_bandwidth_variable}}}", null)
  enforce_bandwidth_control              = try(each.value.zscaler.enforce_bandwidth_control, null)
  enforce_bandwidth_control_variable     = try("{{${each.value.zscaler.enforce_bandwidth_control_variable}}}", null)
  force_ssl_inspection                   = try(each.value.zscaler.force_ssl_inspection, null)
  force_ssl_inspection_variable          = try("{{${each.value.zscaler.force_ssl_inspection_variable}}}", null)
  idle_time                              = try(each.value.zscaler.idle_time, null)
  idle_time_variable                     = try("{{${each.value.zscaler.idle_time_variable}}}", null)
  interface_pairs = try(length(each.value.zscaler.interface_pairs) == 0, true) ? null : [for item in each.value.zscaler.interface_pairs : {
    active_interface        = try(item.active_interface, null)
    active_interface_weight = try(item.active_interface_weight, null)
    backup_interface        = try(item.backup_interface, null)
    backup_interface_weight = try(item.backup_interface_weight, null)
  }]
  interfaces = try(length(each.value.zscaler.interfaces) == 0, true) ? null : [for item in each.value.zscaler.interfaces : {
    auto                             = null # not supported in the UI
    dpd_interval                     = try(item.dpd_interval, null)
    dpd_interval_variable            = try("{{${item.dpd_interval_variable}}}", null)
    dpd_retries                      = try(item.dpd_retries, null)
    dpd_retries_variable             = try("{{${item.dpd_retries_variable}}}", null)
    ike_ciphersuite                  = try(item.ike_ciphersuite, null)
    ike_ciphersuite_variable         = try("{{${item.ike_ciphersuite_variable}}}", null)
    ike_group                        = try(item.ike_group, null)
    ike_group_variable               = try("{{${item.ike_group_variable}}}", null)
    ike_local_id                     = try(item.ike_local_id, null)
    ike_local_id_variable            = try("{{${item.ike_local_id_variable}}}", null)
    ike_rekey_interval               = try(item.ike_rekey_interval, null)
    ike_rekey_interval_variable      = try("{{${item.ike_rekey_interval_variable}}}", null)
    ike_remote_id                    = try(item.ike_remote_id, null)
    ike_remote_id_variable           = try("{{${item.ike_remote_id_variable}}}", null)
    ike_version                      = try(item.ike_version, null)
    ike_version_variable             = try("{{${item.ike_version_variable}}}", null)
    interface_description            = try(item.interface_description, null)
    interface_description_variable   = try("{{${item.interface_description_variable}}}", null)
    interface_name                   = try(item.interface_name, null)
    ipsec_ciphersuite                = try(item.ipsec_ciphersuite, null)
    ipsec_ciphersuite_variable       = try("{{${item.ipsec_ciphersuite_variable}}}", null)
    ipsec_rekey_interval             = try(item.ipsec_rekey_interval, null)
    ipsec_rekey_interval_variable    = try("{{${item.ipsec_rekey_interval_variable}}}", null)
    ipsec_replay_window              = try(item.ipsec_replay_window, null)
    ipsec_replay_window_variable     = try("{{${item.ipsec_replay_window_variable}}}", null)
    ipv4_address                     = try(item.ipv4_address, null)
    ipv4_address_variable            = try("{{${item.ipv4_address_variable}}}", null)
    mtu                              = try(item.mtu, null)
    mtu_variable                     = try("{{${item.mtu_variable}}}", null)
    perfect_forward_secrecy          = try(item.perfect_forward_secrecy, null)
    perfect_forward_secrecy_variable = try("{{${item.perfect_forward_secrecy_variable}}}", null)
    pre_shared_key_dynamic           = null # not supported in the UI
    shutdown                         = try(item.shutdown, null)
    tcp_mss_adjust                   = try(item.tcp_mss_adjust, null)
    tcp_mss_adjust_variable          = try("{{${item.tcp_mss_adjust_variable}}}", null)
    track_enable                     = try(item.track_enable, null)
    tracker                          = try(item.tracker, null)
    tunnel_dc_preference             = try(item.tunnel_dc_preference, null)
    tunnel_destination               = try(item.tunnel_destination, null)
    tunnel_destination_variable      = try("{{${item.tunnel_destination_variable}}}", null)
    tunnel_public_ip                 = try(item.tunnel_public_ip, null)
    tunnel_public_ip_variable        = try("{{${item.tunnel_public_ip_variable}}}", null)
    tunnel_route_via                 = try(item.tunnel_route_via, null)
    tunnel_route_via_variable        = try("{{${item.tunnel_route_via_variable}}}", null)
    tunnel_set                       = try(item.tunnel_set, null)
    tunnel_source                    = try(item.tunnel_source, null)
    tunnel_source_variable           = try("{{${item.tunnel_source_variable}}}", null)
    tunnel_source_interface          = try(item.tunnel_source_interface, null)
    tunnel_source_interface_variable = try("{{${item.tunnel_source_interface_variable}}}", null)
    unnumbered                       = try(item.unnumbered, null)
  }]
  ip_enforced_for_known_browsers          = try(each.value.zscaler.ip_enforced_for_known_browsers, null)
  ip_enforced_for_known_browsers_variable = try("{{${each.value.zscaler.ip_enforced_for_known_browsers_variable}}}", null)
  ips_control                             = try(each.value.zscaler.ips_control, null)
  ips_control_variable                    = try("{{${each.value.zscaler.ips_control_variable}}}", null)
  location_name                           = null # not supported in the UI
  location_name_variable                  = try("{{${each.value.zscaler.location_name_variable}}}", null)
  ofw_enabled                             = try(each.value.zscaler.firewall_enabled, null)
  ofw_enabled_variable                    = try("{{${each.value.zscaler.firewall_enabled_variable}}}", null)
  primary_data_center                     = try(each.value.zscaler.primary_data_center, null)
  primary_data_center_variable            = try("{{${each.value.zscaler.primary_data_center_variable}}}", null)
  refresh_time                            = try(each.value.zscaler.refresh_time, null)
  refresh_time_variable                   = try("{{${each.value.zscaler.refresh_time_variable}}}", null)
  refresh_time_unit                       = try(each.value.zscaler.refresh_time_unit, null)
  refresh_time_unit_variable              = try("{{${each.value.zscaler.refresh_time_unit_variable}}}", null)
  secondary_data_center                   = try(each.value.zscaler.secondary_data_center, null)
  secondary_data_center_variable          = try("{{${each.value.zscaler.secondary_data_center_variable}}}", null)
  src_vpn                                 = try(each.value.zscaler.src_vpn, null)
  sub_locations = try(length(each.value.zscaler.sub_locations) == 0, true) ? null : [for sub_location in each.value.zscaler.sub_locations : {
    name                                   = try(sub_location.name, null)
    name_variable                          = try("{{${sub_location.name_variable}}}", null)
    aup_enabled                            = try(sub_location.aup_enabled, null)
    aup_enabled_variable                   = try("{{${sub_location.aup_enabled_variable}}}", null)
    aup_timeout                            = try(sub_location.aup_timeout, null)
    aup_timeout_variable                   = try("{{${sub_location.aup_timeout_variable}}}", null)
    auth_required                          = try(sub_location.auth_required, null)
    auth_required_variable                 = try("{{${sub_location.auth_required_variable}}}", null)
    block_internet_until_accepted          = try(sub_location.block_internet_until_accepted, null)
    block_internet_until_accepted_variable = try("{{${sub_location.block_internet_until_accepted_variable}}}", null)
    caution_enabled                        = try(sub_location.caution_enabled, null)
    caution_enabled_variable               = try("{{${sub_location.caution_enabled_variable}}}", null)
    display_time_unit                      = try(sub_location.display_time_unit, null)
    display_time_unit_variable             = try("{{${sub_location.display_time_unit_variable}}}", null)
    dn_bandwidth                           = try(sub_location.download_bandwidth, null)
    dn_bandwidth_variable                  = try("{{${sub_location.download_bandwidth_variable}}}", null)
    enforce_bandwidth_control              = try(sub_location.enforce_bandwidth_control, null)
    enforce_bandwidth_control_variable     = try("{{${sub_location.enforce_bandwidth_control_variable}}}", null)
    force_ssl_inspection                   = try(sub_location.force_ssl_inspection, null)
    force_ssl_inspection_variable          = try("{{${sub_location.force_ssl_inspection_variable}}}", null)
    idle_time                              = try(sub_location.idle_time, null)
    idle_time_variable                     = try("{{${sub_location.idle_time_variable}}}", null)
    internal_ip = try(length(sub_location.internal_ips) == 0, true) ? null : [for item in sub_location.internal_ips : {
      internal_ip_value          = try(item.ip_address, null)
      internal_ip_value_variable = try("{{${item.ip_address_variable}}}", null)
    }]
    ip_enforced_for_known_browsers          = try(sub_location.ip_enforced_for_known_browsers, null)
    ip_enforced_for_known_browsers_variable = try("{{${sub_location.ip_enforced_for_known_browsers_variable}}}", null)
    ofw_enabled                             = try(sub_location.firewall_enabled, null)
    ofw_enabled_variable                    = try("{{${sub_location.firewall_enabled_variable}}}", null)
    refresh_time                            = try(sub_location.refresh_time, null)
    refresh_time_variable                   = try("{{${sub_location.refresh_time_variable}}}", null)
    refresh_time_unit                       = try(sub_location.refresh_time_unit, null)
    refresh_time_unit_variable              = try("{{${sub_location.refresh_time_unit_variable}}}", null)
    service_vpn                             = try(sub_location.service_vpn, null)
    service_vpn_variable                    = try("{{${sub_location.service_vpn_variable}}}", null)
    surrogate_ip                            = try(sub_location.surrogate_ip, null)
    surrogate_ip_variable                   = try("{{${sub_location.surrogate_ip_variable}}}", null)
    up_bandwidth                            = try(sub_location.upload_bandwidth, null)
    up_bandwidth_variable                   = try("{{${sub_location.upload_bandwidth_variable}}}", null)
  }]
  surrogate_ip               = try(each.value.zscaler.surrogate_ip, null)
  surrogate_ip_variable      = try("{{${each.value.zscaler.surrogate_ip_variable}}}", null)
  tracker_source_ip          = try(each.value.zscaler.tracker_source_ip, null)
  tracker_source_ip_variable = try("{{${each.value.zscaler.tracker_source_ip_variable}}}", null)
  trackers = try(length(each.value.zscaler.trackers) == 0, true) ? null : [for item in each.value.zscaler.trackers : {
    name                      = try(item.name, null)
    endpoint_api_url          = try(item.endpoint_api_url, null)
    endpoint_api_url_variable = try("{{${item.endpoint_api_url_variable}}}", null)
    interval                  = try(item.interval, null)
    interval_variable         = try("{{${item.interval_variable}}}", null)
    multiplier                = try(item.multiplier, null)
    multiplier_variable       = try("{{${item.multiplier_variable}}}", null)
    threshold                 = try(item.threshold, null)
    threshold_variable        = try("{{${item.threshold_variable}}}", null)
  }]
  up_bandwidth                 = try(each.value.zscaler.upload_bandwidth, null)
  up_bandwidth_variable        = try("{{${each.value.zscaler.upload_bandwidth_variable}}}", null)
  xff_forward_enabled          = try(each.value.zscaler.xff_forward_enabled, null)
  xff_forward_enabled_variable = try("{{${each.value.zscaler.xff_forward_enabled_variable}}}", null)
}
